export const ALL_TREDING_REQUEST = "ALL_TREDING_REQUEST";
export const ALL_TREDING_SUCCESS = "ALL_TREDING_SUCCESS";
export const ALL_TREDING_FAILURE = "ALL_TREDING_FAILURE";

export const ALL_SEARCH_REQUEST = "ALL_SEARCH_REQUEST";
export const ALL_SEARCH_SUCCESS = "ALL_SEARCH_SUCCESS";
export const ALL_SEARCH_FAILURE = "ALL_SEARCH_FAILURE";
