export const MOVIES_TRENDING_REQUEST = "MOVIES_TRENDING_REQUEST";
export const MOVIES_TRENDING_SUCCESS = "MOVIES_TRENDING_SUCCESS";
export const MOVIES_TRENDING_FAILURE = "MOVIES_TRENDING_FAILURE";

export const MOVIES_UPCOMING_REQUEST = "MOVIES_UPCOMING_REQUEST";
export const MOVIES_UPCOMING_SUCCESS = "MOVIES_UPCOMING_SUCCESS";
export const MOVIES_UPCOMING_FAILURE = "MOVIES_UPCOMING_FAILURE";

export const MOVIES_POPULAR_REQUEST = "MOVIES_POPULAR_REQUEST";
export const MOVIES_POPULAR_SUCCESS = "MOVIES_POPULAR_SUCCESS";
export const MOVIES_POPULAR_FAILURE = "MOVIES_POPULAR_FAILURE";

export const MOVIE_DETAILS_REQUEST = "MOVIE_DETAILS_REQUEST";
export const MOVIE_DETAILS_SUCCESS = "MOVIE_DETAILS_SUCCESS";
export const MOVIE_DETAILS_FAILURE = "MOVIE_DETAILS_FAILURE";
