export const SERIES_TRENDING_REQUEST = "SERIES_TRENDING_REQUEST";
export const SERIES_TRENDING_SUCCESS = "SERIES_TRENDING_SUCCESS";
export const SERIES_TRENDING_FAILURE = "SERIES_TRENDING_FAILURE";

export const SERIES_UPCOMING_REQUEST = "SERIES_UPCOMING_REQUEST";
export const SERIES_UPCOMING_SUCCESS = "SERIES_UPCOMING_SUCCESS";
export const SERIES_UPCOMING_FAILURE = "SERIES_UPCOMING_FAILURE";

export const SERIES_POPULAR_REQUEST = "SERIES_POPULAR_REQUEST";
export const SERIES_POPULAR_SUCCESS = "SERIES_POPULAR_SUCCESS";
export const SERIES_POPULAR_FAILURE = "SERIES_POPULAR_FAILURE";

export const SERIES_DETAILS_REQUEST = "SERIES_DETAILS_REQUEST";
export const SERIES_DETAILS_SUCCESS = "SERIES_DETAILS_SUCCESS";
export const SERIES_DETAILS_FAILURE = "SERIES_DETAILS_FAILURE";
