export const USER_EXIST_REQUEST = "USER_EXIST_REQUEST";
export const USER_EXIST_SUCCESS = "USER_EXIST_SUCCESS";
export const USER_EXIST_FAILURE = "USER_EXIST_FAILURE";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";

export const REGISTER_RESEND_OTP_REQUEST = "REGISTER_RESEND_OTP_REQUEST";
export const REGISTER_RESEND_OTP_SUCCESS = "REGISTER_RESEND_OTP_SUCCESS";
export const REGISTER_RESEND_OTP_FAILURE = "REGISTER_RESEND_OTP_FAILURE";

export const VERIFIED_REGISTER_USER_REQUEST = "VERIFIED_REGISTER_USER_REQUEST";
export const VERIFIED_REGISTER_USER_SUCCESS = "VERIFIED_REGISTER_USER_SUCCESS";
export const VERIFIED_REGISTER_USER_FAILURE = "VERIFIED_REGISTER_USER_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGIN_CODE_REQUEST = "LOGIN_CODE_REQUEST";
export const LOGIN_CODE_SUCCESS = "LOGIN_CODE_SUCCESS";
export const LOGIN_CODE_FAILURE = "LOGIN_CODE_FAILURE";

export const LOGIN_CODE_VERIFIED_REQUEST = "LOGIN_CODE_VERIFIED_REQUEST";
export const LOGIN_CODE_VERIFIED_SUCCESS = "LOGIN_CODE_VERIFIED_SUCCESS";
export const LOGIN_CODE_VERIFIED_FAILURE = "LOGIN_CODE_VERIFIED_FAILURE";

export const RESEND_OTP_REQUEST = "RESEND_OTP_REQUEST";
export const RESEND_OTP_SUCCESS = "RESEND_OTP_SUCCESS";
export const RESEND_OTP_FAILURE = "RESEND_OTP_FAILURE";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAILURE = "LOAD_USER_FAILURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILURE = "FORGOT_PASSWORD_FAILURE";

export const FORGOT_PASSWORD_VERIFIED_REQUEST =
  "FORGOT_PASSWORD_VERIFIED_REQUEST";
export const FORGOT_PASSWORD_VERIFIED_SUCCESS =
  "FORGOT_PASSWORD_VERIFIED_SUCCESS";
export const FORGOT_PASSWORD_VERIFIED_FAILURE =
  "FORGOT_PASSWORD_VERIFIED_FAILURE";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILURE = "RESET_PASSWORD_FAILURE";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const CLEAR_MESSAGES = "CLEAR_MESSAGES";
